// Official authorized dealer branches used on brand pages.
// Includes auto-generated entries plus verified local mappings backed by
// official brand/dealer pages and Google Places data.
//
// Used in two places:
//   1) initialShops in mockData.ts — listed alongside other shops, but flagged
//      as "official dealers" so the brand page can pull them by brandSlug.
//   2) Brand pages (/brand/:slug) — branch list with photos & maps.

import type { Category } from "./types";

export interface OfficialDealerBranch {
  id: string;
  slug: string;
  name: string;
  brand: string;
  brandSlug: string;
  area: "شارع الصناعة" | "شارع الربيعي";
  category: Category;
  categories: Category[];
  address: string;
  phone: string | null;
  lat: number | null;
  lng: number | null;
  googleMapsUrl: string | null;
  website: string | null;
  mainImage: string | null;
  officialSourceUrl: string;
}

export const OFFICIAL_DEALER_BRANCHES: OfficialDealerBranch[] = [
  {
    "id": "dealer_samsung_01",
    "slug": "samsung-ayn-alfahad-zayona-branch",
    "name": "Ayn AlFahad (Zayona Branch)",
    "brand": "Samsung",
    "brandSlug": "samsung",
    "area": "شارع الربيعي",
    "category": "Phones",
    "categories": [
      "Phones",
      "Tablets",
      "Smart Devices"
    ],
    "address": "فرع المنصور، مجاور شركة الطيف، 1 14 Ramadan St, Baghdad, Baghdad Governorate, 15011, Iraq",
    "phone": "0783 399 5599",
    "lat": 33.3202699,
    "lng": 44.3380534,
    "googleMapsUrl": "https://maps.google.com/?cid=9605007669365948108&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
    "website": "https://shop.aynalfahad.com/",
    "mainImage": "https://lh3.googleusercontent.com/places/ANXAkqH9elLfxTLglJl43i3QSZC_8l9rbzTjkTCMiPSHRXZxA_k8wOfzrkclYuz-9GgLiM-xlv-3yvEBVtOZ4mNk-kDAHCrjm5_UWXI=s4800-w1529",
    "officialSourceUrl": "https://www.samsung.com/iq_ar/support/apps-services/where-is-the-nearest-samsung-retail-store-located-in-iraq/"
  },
  {
    "id": "dealer_samsung_02",
    "slug": "samsung-ayn-alfahad-ameriya-branch",
    "name": "Ayn AlFahad (Ameriya Branch)",
    "brand": "Samsung",
    "brandSlug": "samsung",
    "area": "شارع الربيعي",
    "category": "Phones",
    "categories": [
      "Phones",
      "Tablets",
      "Smart Devices"
    ],
    "address": "فرع الجامعة، 886F+FMQ، شارع الربيع، Baghdad, Baghdad Governorate, Iraq",
    "phone": "0782 652 5552",
    "lat": 33.3112054,
    "lng": 44.3242409,
    "googleMapsUrl": "https://maps.google.com/?cid=15356325446017686914&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
    "website": "http://www.aynalfahad.com/",
    "mainImage": "https://lh3.googleusercontent.com/place-photos/AJRVUZPcSW4M1wpf8pLEWfTgGczmgq5Dt2mHslUWJnCHAJrH3s1Vk1_AHyCn8rU5PaIsNaQ7VfUaRe0Hyv4kXzYDtPD7xR3PVoWc-_1Uawo7baW3nBP44DaEhzoLUjvxXRwAmawPsMWFTkpUWVC9=s4800-w800",
    "officialSourceUrl": "https://www.samsung.com/iq_ar/support/apps-services/where-is-the-nearest-samsung-retail-store-located-in-iraq/"
  },
  {
    "id": "dealer_samsung_03",
    "slug": "samsung-ayn-alfahad-university-branch",
    "name": "Ayn AlFahad (University Branch)",
    "brand": "Samsung",
    "brandSlug": "samsung",
    "area": "شارع الربيعي",
    "category": "Phones",
    "categories": [
      "Phones",
      "Tablets",
      "Smart Devices"
    ],
    "address": "فرع الجامعة، 886F+FMQ، شارع الربيع، Baghdad, Baghdad Governorate, Iraq",
    "phone": "0782 652 5552",
    "lat": 33.3112054,
    "lng": 44.3242409,
    "googleMapsUrl": "https://maps.google.com/?cid=15356325446017686914&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
    "website": "http://www.aynalfahad.com/",
    "mainImage": "https://lh3.googleusercontent.com/place-photos/AJRVUZPcSW4M1wpf8pLEWfTgGczmgq5Dt2mHslUWJnCHAJrH3s1Vk1_AHyCn8rU5PaIsNaQ7VfUaRe0Hyv4kXzYDtPD7xR3PVoWc-_1Uawo7baW3nBP44DaEhzoLUjvxXRwAmawPsMWFTkpUWVC9=s4800-w800",
    "officialSourceUrl": "https://www.samsung.com/iq_ar/support/apps-services/where-is-the-nearest-samsung-retail-store-located-in-iraq/"
  },
  {
    "id": "dealer_samsung_04",
    "slug": "samsung-ayn-alfahad-mansour-branch",
    "name": "Ayn AlFahad (Mansour Branch)",
    "brand": "Samsung",
    "brandSlug": "samsung",
    "area": "شارع الربيعي",
    "category": "Phones",
    "categories": [
      "Phones",
      "Tablets",
      "Smart Devices"
    ],
    "address": "فرع المنصور، مجاور شركة الطيف، 1 14 Ramadan St, Baghdad, Baghdad Governorate, 15011, Iraq",
    "phone": "0783 399 5599",
    "lat": 33.3202699,
    "lng": 44.3380534,
    "googleMapsUrl": "https://maps.google.com/?cid=9605007669365948108&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
    "website": "https://shop.aynalfahad.com/",
    "mainImage": "https://lh3.googleusercontent.com/places/ANXAkqH9elLfxTLglJl43i3QSZC_8l9rbzTjkTCMiPSHRXZxA_k8wOfzrkclYuz-9GgLiM-xlv-3yvEBVtOZ4mNk-kDAHCrjm5_UWXI=s4800-w1529",
    "officialSourceUrl": "https://www.samsung.com/iq_ar/support/apps-services/where-is-the-nearest-samsung-retail-store-located-in-iraq/"
  },
  {
    "id": "dealer_samsung_05",
    "slug": "samsung-jibal-al-rubaie",
    "name": "Jibal (Al-Rubaie)",
    "brand": "Samsung",
    "brandSlug": "samsung",
    "area": "شارع الربيعي",
    "category": "Phones",
    "categories": [
      "Phones",
      "Tablets",
      "Smart Devices"
    ],
    "address": "Iraq- Baghdad - Zayouna - Al-Rubaie Street، Baghdad, Baghdad Governorate, Iraq",
    "phone": "0750 191 4335",
    "lat": 33.327754,
    "lng": 44.454440999999996,
    "googleMapsUrl": "https://maps.google.com/?cid=2984320555227567189&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
    "website": "http://www.samsung.com/levant/home/",
    "mainImage": "Not found",
    "officialSourceUrl": "https://www.samsung.com/iq_ar/support/apps-services/where-is-the-nearest-samsung-retail-store-located-in-iraq/"
  },
  {
    "id": "dealer_samsung_06",
    "slug": "samsung-jibal-mansour",
    "name": "Jibal (Mansour)",
    "brand": "Samsung",
    "brandSlug": "samsung",
    "area": "شارع الربيعي",
    "category": "Phones",
    "categories": [
      "Phones",
      "Tablets",
      "Smart Devices"
    ],
    "address": "Baghdad, Baghdad Governorate, Iraq",
    "phone": "0780 926 8456",
    "lat": 33.3233125,
    "lng": 44.3380625,
    "googleMapsUrl": "https://maps.google.com/?cid=444821757884113944&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
    "website": "https://www.jibalzone.com/ar",
    "mainImage": "https://lh3.googleusercontent.com/place-photos/AJRVUZPxm1gJymICjDTQfl-7g5hJG3kr-l9vzElbdS_PGTLWHrpblbkDRjIEs7KjVmPSM-absK9F9gKNMesHAaR9qNVRsYIPoKgDghIluIB2PhpFWcUJgKVLjuOdrgifKN4fZz4cKFRJnoboJrBo0w=s4800-w1152",
    "officialSourceUrl": "https://www.samsung.com/iq_ar/support/apps-services/where-is-the-nearest-samsung-retail-store-located-in-iraq/"
  },
  {
    "id": "dealer_samsung_07",
    "slug": "samsung-al-elektroniat-al-thakia-online-sales",
    "name": "AL-Elektroniat Al-thakia (Online Sales)",
    "brand": "Samsung",
    "brandSlug": "samsung",
    "area": "شارع الربيعي",
    "category": "Phones",
    "categories": [
      "Phones",
      "Tablets",
      "Smart Devices"
    ],
    "address": "ساحة التحرير، Electronics market, شارع الجمهورية، Baghdad, Baghdad Governorate, 10001, Iraq",
    "phone": "0770 785 7302",
    "lat": 33.3300141,
    "lng": 44.4077231,
    "googleMapsUrl": "https://maps.google.com/?cid=16537491118114265294&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
    "website": "http://www.alhekmh.com/",
    "mainImage": "https://lh3.googleusercontent.com/place-photos/AJRVUZMqdXi4JI4HaBK2Ej45xK9aMrpgzaYyum19VDsvRUwLIrnPvrAzTZGq63U4Rks0kxbBLrFnbaCF_X-pkIczjV3tAMqR001ILOQ9tVVrhOPYgwrwbx0nIzchU8thJNZMBSs2iVhTj5xmHrjd=s4800-w538",
    "officialSourceUrl": "https://www.samsung.com/iq_ar/support/apps-services/where-is-the-nearest-samsung-retail-store-located-in-iraq/"
  },
  {
    "id": "dealer_samsung_08",
    "slug": "samsung-bayad-al-karkh",
    "name": "Bayad (Al-Karkh)",
    "brand": "Samsung",
    "brandSlug": "samsung",
    "area": "شارع الربيعي",
    "category": "Phones",
    "categories": [
      "Phones",
      "Tablets",
      "Smart Devices"
    ],
    "address": "88FC+J7X, Baghdad, Baghdad Governorate, Iraq",
    "phone": "07903255262",
    "lat": 33.324111699999996,
    "lng": 44.3207289,
    "googleMapsUrl": "https://maps.google.com/?cid=3180738483128640658&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
    "website": "",
    "mainImage": "Not found",
    "officialSourceUrl": "https://www.samsung.com/iq_ar/support/apps-services/where-is-the-nearest-samsung-retail-store-located-in-iraq/"
  },
  {
    "id": "dealer_samsung_09",
    "slug": "samsung-bayad-karada",
    "name": "Bayad (Karada)",
    "brand": "Samsung",
    "brandSlug": "samsung",
    "area": "شارع الربيعي",
    "category": "Phones",
    "categories": [
      "Phones",
      "Tablets",
      "Smart Devices"
    ],
    "address": "8C3F+38W, Baghdad, Baghdad Governorate, Iraq",
    "phone": "0774 030 0006",
    "lat": 33.302775499999996,
    "lng": 44.4233425,
    "googleMapsUrl": "https://maps.google.com/?cid=10754181086280321228&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
    "website": "https://karadastore.iq/",
    "mainImage": "https://lh3.googleusercontent.com/place-photos/AJRVUZMmgUtk8M-oVvWIMmV7FWk1ySW2H4jAglUaIM1pnYp5psP5YIAHZ3Zypxo_PD2WwVJwKdJk8Q95sjzI4cKCG8xlz6k8HucRLGy5BpRciosiutHphWteqch0XITJl0ZiG3kSuZDWCABP_MIfhA=s4800-w1600",
    "officialSourceUrl": "https://www.samsung.com/iq_ar/support/apps-services/where-is-the-nearest-samsung-retail-store-located-in-iraq/"
  },
  {
    "id": "dealer_asus_10",
    "slug": "asus-al--taj-company-for-computer-services-ltd",
    "name": "AL- Taj company for Computer Services Ltd.",
    "brand": "ASUS",
    "brandSlug": "asus",
    "area": "شارع الصناعة",
    "category": "Computing",
    "categories": [
      "Computing",
      "PC Parts",
      "Gaming"
    ],
    "address": "8C6V+GCQ, Baghdad, Baghdad Governorate, Iraq",
    "phone": null,
    "lat": 33.3113399,
    "lng": 44.4436232,
    "googleMapsUrl": "https://maps.google.com/?cid=16612397980917049119&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
    "website": "",
    "mainImage": "https://lh3.googleusercontent.com/place-photos/AJRVUZOcVgR2b7dK5L7l-Lw9pQrhr_-g6sbr_mitoyUDCkkldzBG0Nei9rH4OmKAjyUB25sx37XVFLL3rfK0LLkkk1iXOCxCmn_uNt6uyS8zqETCeRFRRGUhM3C0WXbIOEB_6EFqtUjsF6Sb9vTqTQ=s4800-w1600",
    "officialSourceUrl": "https://www.asus.com/me-en/About_ASUS/where-to-buy/"
  },
  {
    "id": "dealer_asus_11",
    "slug": "asus-al-fawaz-for-computers",
    "name": "Al-Fawaz For Computers",
    "brand": "ASUS",
    "brandSlug": "asus",
    "area": "شارع الصناعة",
    "category": "Computing",
    "categories": [
      "Computing",
      "PC Parts",
      "Gaming"
    ],
    "address": "شارع الصناعة، Baghdad, Baghdad Governorate, Iraq",
    "phone": "0773 630 8499",
    "lat": 33.310488899999996,
    "lng": 44.445679299999995,
    "googleMapsUrl": "https://maps.google.com/?cid=5552536539356039608&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
    "website": "https://alfawaz.com.iq/",
    "mainImage": "https://lh3.googleusercontent.com/place-photos/AJRVUZPyj7DzlmXJdc5j61Jt7AjvuCIFkIalHUN1XX2b2f6Kjxn5e4KJHWE46y2tg0pp92kTWXSGafH_KRi_g_v8xEFr2bbFnkSg57mbH77fN5olA7gvLFe6_E_TOyrNfzYnwvKV0D2hkNagcU1NXAw=s4800-w1600",
    "officialSourceUrl": "https://www.asus.com/me-en/About_ASUS/where-to-buy/"
  },
  {
    "id": "dealer_asus_12",
    "slug": "asus-global-iraq-computer-technologies-llc",
    "name": "Global Iraq Computer Technologies LLC",
    "brand": "ASUS",
    "brandSlug": "asus",
    "area": "شارع الصناعة",
    "category": "Computing",
    "categories": [
      "Computing",
      "PC Parts",
      "Gaming"
    ],
    "address": "داخل فرع النخلة ، عامود14، العالمية للحاسبات، داخل فرع النخله - تسلسل الفرع عامود 14، تسلسل البناية G، شارع الصناعة، Baghdad, Baghdad Governorate, 00000, Iraq",
    "phone": "0772 622 4804",
    "lat": 33.3084527,
    "lng": 44.4464973,
    "googleMapsUrl": "https://maps.google.com/?cid=17178510146165069422&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
    "website": "https://globaliraq.iq/",
    "mainImage": "https://lh3.googleusercontent.com/places/ANXAkqFvez9pyLkD6kCoJxeO_qhasjn8KsipQkASISIA68LB02NvWIjdWeXXKsg7GId7fHnbD_4EJ96eGSeToY8nC9Noxe9xGihDwts=s4800-w1600",
    "officialSourceUrl": "https://www.asus.com/me-en/About_ASUS/where-to-buy/"
  },
  {
    "id": "dealer_asus_13",
    "slug": "asus-dhakaa-al-shabaka-for-general-trading-coll-spider-net",
    "name": "DHAKAA AL-SHABAKA FOR General Trading CO.L.L (Spider Net)",
    "brand": "ASUS",
    "brandSlug": "asus",
    "area": "شارع الصناعة",
    "category": "Computing",
    "categories": [
      "Computing",
      "PC Parts",
      "Gaming"
    ],
    "address": "Alsina street, Baghdad, Baghdad Governorate, Iraq",
    "phone": "+964 7707894921",
    "lat": 33.3093923,
    "lng": 44.4477346,
    "googleMapsUrl": "https://maps.google.com/?cid=5398908267229662692&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
    "website": "http://spniq.com/",
    "mainImage": "https://lh3.googleusercontent.com/place-photos/AJRVUZN9bX8FLTHW-nBKzrGIiK0U1w5ZWmKEhe27hwQvBHPjSPXIGzNiuazCHZvXc0KZb0hqH64ErTt69fidzhXcBbHp0iO1wRLNru86x5gzqkqfnxvEk9VztPfT69KFAxDq-iPpAcMJau8zPzd5qA=s4800-w1080",
    "officialSourceUrl": "https://www.asus.com/me-en/About_ASUS/where-to-buy/"
  },
  {
    "id": "dealer_asus_14",
    "slug": "asus-alityan-alshamelah",
    "name": "ALITYAN ALSHAMELAH",
    "brand": "ASUS",
    "brandSlug": "asus",
    "area": "شارع الصناعة",
    "category": "Computing",
    "categories": [
      "Computing",
      "PC Parts",
      "Gaming"
    ],
    "address": "Baghdad, Baghdad Governorate, Iraq",
    "phone": "0772 344 0578",
    "lat": 33.3095099,
    "lng": 44.4473589,
    "googleMapsUrl": "https://maps.google.com/?cid=11421175266867573723&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
    "website": "http://alityan.com/",
    "mainImage": "https://lh3.googleusercontent.com/places/ANXAkqET3Zv_mJL-ILwLr7DUU-ePCM-gFXqydkKciedNTFD7OTBRVfNb341l5JeEJMDr_t4aaI_tnw_Udkx8lCvdW9QCrb_brsoUIKI=s4800-w1600",
    "officialSourceUrl": "https://www.asus.com/me-en/About_ASUS/where-to-buy/"
  },
  {
    "id": "dealer_asus_15",
    "slug": "asus-support-technology",
    "name": "SUPPORT TECHNOLOGY",
    "brand": "ASUS",
    "brandSlug": "asus",
    "area": "شارع الصناعة",
    "category": "Computing",
    "categories": [
      "Computing",
      "PC Parts",
      "Gaming"
    ],
    "address": "مقابل الجامعة التكنولوجية، شارع الصناعة، Baghdad, Baghdad Governorate, Iraq",
    "phone": "0770 623 5052",
    "lat": 33.3106522,
    "lng": 44.4443207,
    "googleMapsUrl": "https://maps.google.com/?cid=3970109958376840223&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
    "website": "http://www.advantechco.com/",
    "mainImage": "https://lh3.googleusercontent.com/places/ANXAkqHr12-5c8qagbLHhYpjS_x9DEJHslWVgSVHqt4W1IpYl6ZWUCfSnzfgus2Xq8tTNuAQEIBQh3NLnXP1Hq7Xu8n8wCs0nriur1Q=s4800-w959",
    "officialSourceUrl": "https://www.asus.com/me-en/About_ASUS/where-to-buy/"
  },
  {
    "id": "dealer_honor_16",
    "slug": "honor-mateen-phone",
    "name": "Mateen Phone",
    "brand": "HONOR",
    "brandSlug": "honor",
    "area": "شارع الربيعي",
    "category": "Phones",
    "categories": [
      "Phones",
      "Tablets",
      "Accessories"
    ],
    "address": "Zayouna, Baghdad, Baghdad Governorate, 11123, Iraq",
    "phone": "0771 398 8845",
    "lat": 33.3265625,
    "lng": 44.4530625,
    "googleMapsUrl": "https://maps.google.com/?cid=5929624478368449828&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
    "website": "",
    "mainImage": "https://lh3.googleusercontent.com/place-photos/AJRVUZNG3yMN-O4qcfpV9Sk0KYHe6rsH8DCFMxllbfZNbZZ_oQcBqmKugOI_ccmIxiD_rRfctFJPd_3eGJuNrQBMNtznESyemWlJ9FdVXjXHxe6R_4rpvpFn9pupbfap7gULzKqzqZf0XqTXJ32D1Q=s4800-w1600",
    "officialSourceUrl": "https://www.honor.com/iq/events/where-to-buy-eid-offers/"
  },
  {
    "id": "dealer_honor_17",
    "slug": "honor-pc-phone-3",
    "name": "PC Phone 3",
    "brand": "HONOR",
    "brandSlug": "honor",
    "area": "شارع الربيعي",
    "category": "Phones",
    "categories": [
      "Phones",
      "Tablets",
      "Accessories"
    ],
    "address": "14 Ramadan St, Baghdad, Baghdad Governorate, Iraq",
    "phone": "0771 775 5544",
    "lat": 33.320294499999996,
    "lng": 44.3379578,
    "googleMapsUrl": "https://maps.google.com/?cid=5503433478381268821&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
    "website": "https://www.facebook.com/3Store.IQ/",
    "mainImage": "https://lh3.googleusercontent.com/places/ANXAkqHH_A4ghNo_8XBXIs8DkA-ks6FXlxhfHTGS5HtGeuIETPghdDppX_bMY3iPkmXOt7ph1nmZoBi2QgtXdZ-0Cpvqxg71HEFnbrs=s4800-w703",
    "officialSourceUrl": "https://www.honor.com/iq/events/where-to-buy-eid-offers/"
  },
  {
    "id": "dealer_honor_18",
    "slug": "honor-al-bahar",
    "name": "Al Bahar",
    "brand": "HONOR",
    "brandSlug": "honor",
    "area": "شارع الربيعي",
    "category": "Phones",
    "categories": [
      "Phones",
      "Tablets",
      "Accessories"
    ],
    "address": "Masbah St, Baghdad, Baghdad Governorate, 10001, Iraq",
    "phone": "0773 100 9900",
    "lat": 33.2954858,
    "lng": 44.4354714,
    "googleMapsUrl": "https://maps.google.com/?cid=14813931950533660408&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
    "website": "https://www.beharalmarjan.com/",
    "mainImage": "https://lh3.googleusercontent.com/place-photos/AJRVUZO79GZCJlXMkagv0cyCBptpIzOKdqau1NMom3-O7WWhbEIuyUbe2Qjs-xvQee9iuD8geePNES77Vni0Vq41DuNQiCmXpxnvpANvHBjgHch0Xl_RwQ6vRJIEc3xvm6AI_P_bdC7uzJmEZLM_=s4800-w1600",
    "officialSourceUrl": "https://www.honor.com/iq/events/where-to-buy-eid-offers/"
  },
  {
    "id": "dealer_honor_19",
    "slug": "honor-al-markaz-al-duwaly",
    "name": "Al Markaz Al Duwaly",
    "brand": "HONOR",
    "brandSlug": "honor",
    "area": "شارع الربيعي",
    "category": "Phones",
    "categories": [
      "Phones",
      "Tablets",
      "Accessories"
    ],
    "address": "Aden Sq, Baghdad, Baghdad Governorate, Iraq",
    "phone": "0771 112 1319",
    "lat": 33.3568735,
    "lng": 44.338892699999995,
    "googleMapsUrl": "https://maps.google.com/?cid=8753616856486265978&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
    "website": "",
    "mainImage": "https://lh3.googleusercontent.com/place-photos/AJRVUZMOrzV_DdxH4DxQR7nMnLb4vlqIUA61QomZtCeVd0jdpwNd6VET-Eojpysp2vHvcjvtyv5jW5M2GcORLgO-Th6HNPm_xVvGMfpElMGq-TTxE7Q3sS0kYsqxpXHErzL80PC4daY8SZkpxek-kg=s4800-w1600",
    "officialSourceUrl": "https://www.honor.com/iq/events/where-to-buy-eid-offers/"
  },
  {
    "id": "dealer_honor_20",
    "slug": "honor-jibal-zone-zayona",
    "name": "Jibal Zone Zayona",
    "brand": "HONOR",
    "brandSlug": "honor",
    "area": "شارع الربيعي",
    "category": "Phones",
    "categories": [
      "Phones",
      "Tablets",
      "Accessories"
    ],
    "address": "Baghdad, Baghdad Governorate, Iraq",
    "phone": "0780 926 8456",
    "lat": 33.3233125,
    "lng": 44.3380625,
    "googleMapsUrl": "https://maps.google.com/?cid=444821757884113944&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
    "website": "https://www.jibalzone.com/ar",
    "mainImage": "https://lh3.googleusercontent.com/place-photos/AJRVUZPxm1gJymICjDTQfl-7g5hJG3kr-l9vzElbdS_PGTLWHrpblbkDRjIEs7KjVmPSM-absK9F9gKNMesHAaR9qNVRsYIPoKgDghIluIB2PhpFWcUJgKVLjuOdrgifKN4fZz4cKFRJnoboJrBo0w=s4800-w1152",
    "officialSourceUrl": "https://www.honor.com/iq/events/where-to-buy-eid-offers/"
  },
  {
    "id": "dealer_honor_21",
    "slug": "honor-jibal-zone-mounsor",
    "name": "Jibal Zone Mounsor",
    "brand": "HONOR",
    "brandSlug": "honor",
    "area": "شارع الربيعي",
    "category": "Phones",
    "categories": [
      "Phones",
      "Tablets",
      "Accessories"
    ],
    "address": "Baghdad, Baghdad Governorate, Iraq",
    "phone": "0780 926 8456",
    "lat": 33.3233125,
    "lng": 44.3380625,
    "googleMapsUrl": "https://maps.google.com/?cid=444821757884113944&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
    "website": "https://www.jibalzone.com/ar",
    "mainImage": "https://lh3.googleusercontent.com/place-photos/AJRVUZPxm1gJymICjDTQfl-7g5hJG3kr-l9vzElbdS_PGTLWHrpblbkDRjIEs7KjVmPSM-absK9F9gKNMesHAaR9qNVRsYIPoKgDghIluIB2PhpFWcUJgKVLjuOdrgifKN4fZz4cKFRJnoboJrBo0w=s4800-w1152",
    "officialSourceUrl": "https://www.honor.com/iq/events/where-to-buy-eid-offers/"
  },
  {
    "id": "dealer_honor_22",
    "slug": "honor-t-mobile",
    "name": "T Mobile",
    "brand": "HONOR",
    "brandSlug": "honor",
    "area": "شارع الربيعي",
    "category": "Phones",
    "categories": [
      "Phones",
      "Tablets",
      "Accessories"
    ],
    "address": "14 Ramadan St, Baghdad, Baghdad Governorate, Iraq",
    "phone": "0781 555 5525",
    "lat": 33.319186,
    "lng": 44.3379347,
    "googleMapsUrl": "https://maps.google.com/?cid=12679032257561492532&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
    "website": "https://instagram.com/t_mobilecenter1",
    "mainImage": "https://lh3.googleusercontent.com/places/ANXAkqEKNUwwD_DZCzYc4jFoIp5xcZqRxz_Y8dHujKvlrI-s4stiYjWFZkMWGcvPAOU7p0krunv3qKo9-9GsZ68OASkJbBG6OXjIjeY=s4800-w1600",
    "officialSourceUrl": "https://www.honor.com/iq/events/where-to-buy-eid-offers/"
  },
  {
    "id": "dealer_honor_23",
    "slug": "honor-smart",
    "name": "SMART",
    "brand": "HONOR",
    "brandSlug": "honor",
    "area": "شارع الربيعي",
    "category": "Phones",
    "categories": [
      "Phones",
      "Tablets",
      "Accessories"
    ],
    "address": "14 Ramadan St, Baghdad, Baghdad Governorate, Iraq",
    "phone": "0771 555 0422",
    "lat": 33.318384099999996,
    "lng": 44.3395929,
    "googleMapsUrl": "https://maps.google.com/?cid=13268956735289283007&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
    "website": "http://www.facebook.com/smart.iq2",
    "mainImage": "https://lh3.googleusercontent.com/places/ANXAkqHtR6I5ZswVcD7rgduAaOJ8pF6HtMOa1bE0EgIt7mexIiUoQ1iGYQicZvqIIkKaQ9DJPuI-SB-cw9y-SAGcKuNc4UVzD1dzIuk=s4800-w720",
    "officialSourceUrl": "https://www.honor.com/iq/events/where-to-buy-eid-offers/"
  },
  {
    "id": "dealer_honor_24",
    "slug": "honor-miraco",
    "name": "Miraco",
    "brand": "HONOR",
    "brandSlug": "honor",
    "area": "شارع الربيعي",
    "category": "Phones",
    "categories": [
      "Phones",
      "Tablets",
      "Accessories"
    ],
    "address": "Outer Karrada, Baghdad, Baghdad Governorate, Iraq",
    "phone": "0781 946 6660",
    "lat": 33.2965048,
    "lng": 44.4264656,
    "googleMapsUrl": "https://maps.google.com/?cid=10373939932835563888&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
    "website": "",
    "mainImage": "https://lh3.googleusercontent.com/places/ANXAkqH9r0QBhNzkmEq1J5lUQKOKsinSkMj2Gpf4UZ9gg6w0q5qiQzDc1r4qjIxauhxEKP5ntT4UEmJSaeBp99-yTtpiw3uNrq06q3E=s4800-w1600",
    "officialSourceUrl": "https://www.honor.com/iq/events/where-to-buy-eid-offers/"
  },
  {
    "id": "dealer_honor_25",
    "slug": "honor-ahmad-al-rubaye",
    "name": "Ahmad Al Rubaye",
    "brand": "HONOR",
    "brandSlug": "honor",
    "area": "شارع الربيعي",
    "category": "Phones",
    "categories": [
      "Phones",
      "Tablets",
      "Accessories"
    ],
    "address": "8C2F+R78, Baghdad, Baghdad Governorate, Iraq",
    "phone": "0790 190 5596",
    "lat": 33.3020376,
    "lng": 44.423218299999995,
    "googleMapsUrl": "https://maps.google.com/?cid=14206520101973156830&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
    "website": "http://www.alrubeiygroup.com/",
    "mainImage": "https://lh3.googleusercontent.com/place-photos/AJRVUZP_oLjU9hGTrsW1RBpika6LcCqzOQlJyns0t7WDV02-EjDNqvu7r5IWCUthPQzo5lhgMBwt0yrw14gpq9iKxNhLTRkxWbUOMULXUEUU_RKwrUA-xs9v-X9mu53Z1TgFRLl4pcVppxKnt6vozw=s4800-w1600",
    "officialSourceUrl": "https://www.honor.com/iq/events/where-to-buy-eid-offers/"
  },
  {
    "id": "dealer_honor_26",
    "slug": "honor-phone-g",
    "name": "Phone G",
    "brand": "HONOR",
    "brandSlug": "honor",
    "area": "شارع الربيعي",
    "category": "Phones",
    "categories": [
      "Phones",
      "Tablets",
      "Accessories"
    ],
    "address": "8CCX+RGC، شارع الربيعي، Baghdad, Baghdad Governorate, 10091, Iraq",
    "phone": "0772 227 7741",
    "lat": 33.3220532,
    "lng": 44.448754799999996,
    "googleMapsUrl": "https://maps.google.com/?cid=60959017039439506&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
    "website": "",
    "mainImage": "https://lh3.googleusercontent.com/place-photos/AJRVUZM2BOwOoipxylQ6-n-MrZ6_ob2yM5NDEqRtwEYeHA4zmeUri230vKjwQs7Ed3vyk24eqk0usFxoG6l2Rf9mS2z1jGaIlUDE7zss92rRM56FP7ruEwDhumh3wqJqMRKs1jEUPh_VCKNDc8xQ=s4800-w1136",
    "officialSourceUrl": "https://www.honor.com/iq/events/where-to-buy-eid-offers/"
  },
  {
    "id": "dealer_honor_27",
    "slug": "honor-target-center",
    "name": "Target Center",
    "brand": "HONOR",
    "brandSlug": "honor",
    "area": "شارع الربيعي",
    "category": "Phones",
    "categories": [
      "Phones",
      "Tablets",
      "Accessories"
    ],
    "address": "Asmai Street, Baghdad, Baghdad Governorate, 10053, Iraq",
    "phone": "0772 266 3800",
    "lat": 33.3759741,
    "lng": 44.372178299999995,
    "googleMapsUrl": "https://maps.google.com/?cid=17374171170206543356&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
    "website": "https://www.facebook.com/TargetElectroStore/",
    "mainImage": "https://lh3.googleusercontent.com/places/ANXAkqFCBzcduyY3maXlAk8HVI8thJzNSD4spO22Ye2qAEUH-Nv-kW6pZAn-unOG8yWsQ3N3Cj9aY48-vsXGShUye1cOPCfLfbcVsuk=s4800-w960",
    "officialSourceUrl": "https://www.honor.com/iq/events/where-to-buy-eid-offers/"
  },
  {
    "id": "dealer_honor_28",
    "slug": "honor-al-qalaa",
    "name": "Al Qalaa",
    "brand": "HONOR",
    "brandSlug": "honor",
    "area": "شارع الربيعي",
    "category": "Phones",
    "categories": [
      "Phones",
      "Tablets",
      "Accessories"
    ],
    "address": "باب الدروازة، ساحة قريش، Baghdad, Baghdad Governorate, Iraq",
    "phone": "0772 222 6763",
    "lat": 33.3774635,
    "lng": 44.3420346,
    "googleMapsUrl": "https://maps.google.com/?cid=11855955879427914444&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
    "website": "",
    "mainImage": "https://lh3.googleusercontent.com/place-photos/AJRVUZMd57MEwMiCNTxx2YXbK1l04nUyYBBTkfeWC-RhC27ia9RS3aKiIuoFTz0y6mV1s7xDCC5yS6VuhlQxNraPpnVZedBI5yvkk5e_9eIv-RZzj501mJUW8Rb-0Fu9RNhO7qsa516kv0A1ZiorvOk=s4800-w1080",
    "officialSourceUrl": "https://www.honor.com/iq/events/where-to-buy-eid-offers/"
  }
  ,
  // ===== Apple Authorized Resellers (source: locate.apple.com/iq) =====
  {
    id: "dealer_apple_01",
    slug: "apple-icenter-al-rubaie",
    name: "iCenter — Al Rubaie",
    brand: "Apple",
    brandSlug: "apple",
    area: "شارع الربيعي",
    category: "Phones",
    categories: ["Phones", "Tablets", "Smart Devices", "Accessories"],
    address: "Zayona, Al-Rubaie St, Baghdad, Iraq",
    phone: "0770 728 2211",
    lat: 33.3222994,
    lng: 44.4490161,
    googleMapsUrl: "https://maps.google.com/?cid=2971659340730955523",
    website: "https://www.icenter-iraq.com/",
    mainImage: "https://lh3.googleusercontent.com/places/ANXAkqHUACdtdiEXiEl96lwCCHB2ttkErhyFeqWsiPDKWzJ1MbpYesqoqGMCiM_VesTNULKlnHB2HCQFUN1ibKTylxreU0QOrH_L4-Y=s4800-w1600",
    officialSourceUrl: "https://locate.apple.com/iq/en/sales",
  },
  {
    id: "dealer_apple_02",
    slug: "apple-jibal-zone-mansour",
    name: "Jibal Zone — Al-Mansour 14 Ramadan",
    brand: "Apple",
    brandSlug: "apple",
    area: "شارع الربيعي",
    category: "Phones",
    categories: ["Phones", "Tablets", "Accessories"],
    address: "Al-Mansour 14 Ramadan, Baghdad, Iraq",
    phone: "0780 926 8456",
    lat: 33.3233125,
    lng: 44.3380625,
    googleMapsUrl: "https://maps.google.com/?cid=444821757884113944",
    website: "https://www.jibalzone.com/ar",
    mainImage: "https://lh3.googleusercontent.com/place-photos/AJRVUZPxm1gJymICjDTQfl-7g5hJG3kr-l9vzElbdS_PGTLWHrpblbkDRjIEs7KjVmPSM-absK9F9gKNMesHAaR9qNVRsYIPoKgDghIluIB2PhpFWcUJgKVLjuOdrgifKN4fZz4cKFRJnoboJrBo0w=s4800-w1152",
    officialSourceUrl: "https://locate.apple.com/iq/en/sales",
  },
  {
    id: "dealer_apple_03",
    slug: "apple-icenter-mansour",
    name: "iCenter — Mansour",
    brand: "Apple",
    brandSlug: "apple",
    area: "شارع الربيعي",
    category: "Phones",
    categories: ["Phones", "Tablets", "Smart Devices", "Accessories"],
    address: "Al Mansour, Daoudy, Baghdad, Iraq",
    phone: "0770 728 2211",
    lat: 33.3184375,
    lng: 44.339437499999995,
    googleMapsUrl: "https://maps.google.com/?cid=12528612969389065235",
    website: "https://www.icenter-iraq.com/",
    mainImage: "https://lh3.googleusercontent.com/place-photos/AJRVUZP8STMoGFqoWBcJAaz2TtGj7_jMWfdNa3NJoFYRfd1qoMNZLJZo9dWKAv8ujHBt74PN6Z_JefuF-i_z-spTq63fwzoXQnckH4rZr66kCGFstfnNM_0vld4QJrhKGZzdH-GNHccb8Rh0AmaQ6fvrY1NI=s4800-w1600",
    officialSourceUrl: "https://locate.apple.com/iq/en/sales",
  },
  {
    id: "dealer_apple_04",
    slug: "apple-point-mansour",
    name: "Point — Mansour",
    brand: "Apple",
    brandSlug: "apple",
    area: "شارع الربيعي",
    category: "Phones",
    categories: ["Phones", "Tablets", "Accessories"],
    address: "14 Ramadan, Baghdad, Iraq",
    phone: null,
    lat: 33.3149075,
    lng: 44.3380676,
    googleMapsUrl: "https://maps.google.com/?q=14+Ramadan+St,+Baghdad",
    website: null,
    mainImage: "https://lh3.googleusercontent.com/place-photos/AJRVUZNNLu9InjWCpPe_VkuRX1bgyVBEQJERjDz1-mpVAbu2qRJRwpu13w8E105ZQCvrhOi5JGr-ir5k33cVa2NEsVWswd7I7Zog2xz6G-4QMNPW-PlyaGVxSRBMvA1cr9lA2KSUhmWApE4kbWCQ=s4800-w1600",
    officialSourceUrl: "https://locate.apple.com/iq/en/sales",
  },
  {
    id: "dealer_apple_05",
    slug: "apple-icenter-baghdad",
    name: "iCenter Baghdad — Rubaie",
    brand: "Apple",
    brandSlug: "apple",
    area: "شارع الربيعي",
    category: "Phones",
    categories: ["Phones", "Tablets", "Smart Devices", "Accessories"],
    address: "Rubaie St, Baghdad, Iraq",
    phone: "0770 728 2211",
    lat: 33.3222994,
    lng: 44.4490161,
    googleMapsUrl: "https://maps.google.com/?cid=2971659340730955523",
    website: "https://www.icenter-iraq.com/",
    mainImage: "https://lh3.googleusercontent.com/places/ANXAkqHUACdtdiEXiEl96lwCCHB2ttkErhyFeqWsiPDKWzJ1MbpYesqoqGMCiM_VesTNULKlnHB2HCQFUN1ibKTylxreU0QOrH_L4-Y=s4800-w1600",
    officialSourceUrl: "https://locate.apple.com/iq/en/sales",
  },
  {
    id: "dealer_apple_06",
    slug: "apple-jibal-zone-jawhara",
    name: "Jibal Zone — Near Jawhara Mall",
    brand: "Apple",
    brandSlug: "apple",
    area: "شارع الربيعي",
    category: "Phones",
    categories: ["Phones", "Tablets", "Accessories"],
    address: "Al-Rubaee Street, Baghdad, Iraq",
    phone: "0780 926 8456",
    lat: 33.3233125,
    lng: 44.3380625,
    googleMapsUrl: "https://maps.google.com/?cid=444821757884113944",
    website: "https://www.jibalzone.com/ar",
    mainImage: "https://lh3.googleusercontent.com/place-photos/AJRVUZPxm1gJymICjDTQfl-7g5hJG3kr-l9vzElbdS_PGTLWHrpblbkDRjIEs7KjVmPSM-absK9F9gKNMesHAaR9qNVRsYIPoKgDghIluIB2PhpFWcUJgKVLjuOdrgifKN4fZz4cKFRJnoboJrBo0w=s4800-w1152",
    officialSourceUrl: "https://locate.apple.com/iq/en/sales",
  },
  {
    id: "dealer_apple_07",
    slug: "apple-istyle-arasat",
    name: "iSTYLE — Arasat Al Hindiya",
    brand: "Apple",
    brandSlug: "apple",
    area: "شارع الربيعي",
    category: "Phones",
    categories: ["Phones", "Tablets", "Smart Devices", "Accessories"],
    address: "Arasat Al Hindiya Main Street, Karada, Baghdad, Iraq",
    phone: "0780 000 2511",
    lat: 33.290935999999995,
    lng: 44.420021,
    googleMapsUrl: "https://maps.google.com/?cid=7366567776144375023",
    website: "https://istyle.iq/",
    mainImage: "https://lh3.googleusercontent.com/places/ANXAkqHRT82GXubHRlxIF0DFho5bbVw89-s84Vhaw8aWo4dCP2Jt1e3f4QncVJ_NOMBTEt9bEntUW-D1c1bLgSuPyeznc_s9R6r-xBk=s4800-w480",
    officialSourceUrl: "https://locate.apple.com/iq/en/sales",
  },
  {
    id: "dealer_apple_08",
    slug: "apple-al-nabaa-sinaa",
    name: "AL-NABAA — Al Sinaa Street",
    brand: "Apple",
    brandSlug: "apple",
    area: "شارع الصناعة",
    category: "Phones",
    categories: ["Phones", "Tablets", "Smart Devices", "Accessories", "Computing"],
    address: "Al Sinaa Street, Baghdad, Iraq",
    phone: "0774 802 5119",
    lat: 33.309342,
    lng: 44.4467535,
    googleMapsUrl: "https://maps.google.com/?cid=15006527018926052084",
    website: "https://www.alnabaa.com/",
    mainImage: "https://lh3.googleusercontent.com/place-photos/AJRVUZO6VNwRO1XfKF-O-D4kVogapNfHbpp1cwEtIQ2RTQCKjuOq9JyXgTXrY50u4n2s8HusJKe0BgFdF4sPedo9gU5wkCcn8jW-ztbCfzFJNfP0XOMtSGjPSFU80cIymB8PSshqGFfCK6KFE6V37g=s4800-w1600",
    officialSourceUrl: "https://locate.apple.com/iq/en/sales",
  },
  {
    id: "dealer_apple_09",
    slug: "apple-point-mobile-binook",
    name: "Point Mobile — Binook",
    brand: "Apple",
    brandSlug: "apple",
    area: "شارع الربيعي",
    category: "Phones",
    categories: ["Phones", "Tablets", "Accessories"],
    address: "Al Binook, 319, 11, 4, Baghdad, Iraq",
    phone: "0773 478 3731",
    lat: 33.3184086,
    lng: 44.339430899999996,
    googleMapsUrl: "https://maps.google.com/?cid=8130043492291143818",
    website: "https://pointmobs.com/",
    mainImage: "https://lh3.googleusercontent.com/place-photos/AJRVUZML7CKsFJIyBP8dl8QsVwQ49xK96Aii__XkNmeiOdp0_c3KFngRjJs5h-gHbhyHTg7a5jvt_-WoQ0BcSTh3BQ1x3v_8XxYn8ZFc8yfwcbCjixT2SUp0nZnzEIMUcHRt54iAUv0zNo05E-09AHy2WmhLXQ=s4800-w1600",
    officialSourceUrl: "https://locate.apple.com/iq/en/sales",
  },
  {
    id: "dealer_apple_10",
    slug: "apple-master-store-jamaa",
    name: "Master Store — Al Jamaa",
    brand: "Apple",
    brandSlug: "apple",
    area: "شارع الربيعي",
    category: "Phones",
    categories: ["Phones", "Tablets", "Smart Devices", "Accessories"],
    address: "Hay Al Jamaa, Baghdad, Iraq",
    phone: "0772 618 0662",
    lat: 33.3104653,
    lng: 44.4366413,
    googleMapsUrl: "https://maps.google.com/?cid=6190427107404393447",
    website: "https://www.masterstoreiq.com/",
    mainImage: "https://lh3.googleusercontent.com/places/ANXAkqEwGZQM3YPXCK5NcIvh3_5ONYxq6AZ_RKhQkNK5_vpQ4AEXKu53pxZee4zvp_2Egvy-hTJgfw0oFwv4C7eoRhmGbjSZdwNvl4E=s4800-w676",
    officialSourceUrl: "https://locate.apple.com/iq/en/sales",
  },
  {
    id: "dealer_apple_11",
    slug: "apple-istyle-iraq-mall",
    name: "iSTYLE — Iraq Mall (Dora)",
    brand: "Apple",
    brandSlug: "apple",
    area: "شارع الربيعي",
    category: "Phones",
    categories: ["Phones", "Tablets", "Smart Devices", "Accessories"],
    address: "Baghdad Mall, Dora, Iraq",
    phone: "0780 000 2511",
    lat: 33.2660371,
    lng: 44.416278,
    googleMapsUrl: "https://maps.google.com/?cid=5665502218258894740",
    website: "https://www.istyle.iq/",
    mainImage: "https://lh3.googleusercontent.com/places/ANXAkqGSHZ_JgHygJi50tU3HRknk5yWKvmjMSYtCXLEEkPYza4y0sqsbf57VXQeQct3CAIkmEbbltGMpvLxCkJAecm0DHCgKTVzQF2o=s4800-w480",
    officialSourceUrl: "https://locate.apple.com/iq/en/sales",
  },
  {
    id: "dealer_apple_12",
    slug: "apple-point-saydia",
    name: "Point — Saydia",
    brand: "Apple",
    brandSlug: "apple",
    area: "شارع الربيعي",
    category: "Phones",
    categories: ["Phones", "Tablets", "Accessories"],
    address: "Al Saydiya — Tijari Street, Baghdad, Iraq",
    phone: "0773 115 5887",
    lat: 33.2635625,
    lng: 44.352687499999995,
    googleMapsUrl: "https://maps.google.com/?cid=6642359561434051515",
    website: null,
    mainImage: "https://lh3.googleusercontent.com/place-photos/AJRVUZPWw-t8e0pJlPneJrqvLQV0cx9b_i-WFcNtugSzYl2epeZb0G03LKwJaQDcWcsNqXQCDTDO3-nrdoU9IpLXPQAYEQHuwfDWY8SBIwQFn_kIg5pzDh8ZPXGhSS6wjwBqLn-ecxYdiWYS-8LC=s4800-w1600",
    officialSourceUrl: "https://locate.apple.com/iq/en/sales",
  },
  {
    id: "dealer_apple_13",
    slug: "apple-icenter-naqeeb",
    name: "iCenter — Al Naqeeb (Karbala)",
    brand: "Apple",
    brandSlug: "apple",
    area: "شارع الربيعي",
    category: "Phones",
    categories: ["Phones", "Tablets", "Smart Devices", "Accessories"],
    address: "Al Naqeeb Street, Karbala, Iraq",
    phone: "0770 728 2211",
    lat: 32.6160,
    lng: 44.0244,
    googleMapsUrl: "https://maps.google.com/?cid=12528612969389065235",
    website: "https://www.icenter-iraq.com/",
    mainImage: "https://lh3.googleusercontent.com/place-photos/AJRVUZP8STMoGFqoWBcJAaz2TtGj7_jMWfdNa3NJoFYRfd1qoMNZLJZo9dWKAv8ujHBt74PN6Z_JefuF-i_z-spTq63fwzoXQnckH4rZr66kCGFstfnNM_0vld4QJrhKGZzdH-GNHccb8Rh0AmaQ6fvrY1NI=s4800-w1600",
    officialSourceUrl: "https://locate.apple.com/iq/en/sales",
  },
  {
    id: "dealer_apple_14",
    slug: "apple-al-nabaa-babil",
    name: "AL-NABAA — Babil",
    brand: "Apple",
    brandSlug: "apple",
    area: "شارع الصناعة",
    category: "Phones",
    categories: ["Phones", "Tablets", "Smart Devices", "Accessories", "Computing"],
    address: "Babil, Iraq",
    phone: "0771 308 2627",
    lat: 32.488092099999996,
    lng: 44.4277284,
    googleMapsUrl: "https://maps.google.com/?cid=8229241705751705273",
    website: "http://alnabaa.com/",
    mainImage: "https://lh3.googleusercontent.com/place-photos/AJRVUZMikm6AoN0SCiH1jjgBq6qY8LcwgvQc5Ap4u755hOqib88l3yYHGyy2qWcyU8guqKuOA42TezETmH0fNUCF6Hzxw49GDBAxi8Xj1nnFwyxQF03frxtX0UleH8GqrnzqWPeaAfHg3uwrcUkjPdM=s4800-w1600",
    officialSourceUrl: "https://locate.apple.com/iq/en/sales",
  },
  {
    id: "dealer_adata_01",
    slug: "adata-al-nabaa-baghdad-hq",
    name: "AL-NABAA — Baghdad HQ",
    brand: "ADATA",
    brandSlug: "adata",
    area: "شارع الصناعة",
    category: "PC Parts",
    categories: ["PC Parts", "Computing", "Accessories", "Chargers"],
    address: "Al Nabaa Group Building, Al Senaha St, Baghdad, Baghdad Governorate, 35068, Iraq",
    phone: "0774 802 5119",
    lat: 33.309342,
    lng: 44.4467535,
    googleMapsUrl: "https://maps.google.com/?cid=15006527018926052084",
    website: "https://www.alnabaa.com/",
    mainImage: "https://lh3.googleusercontent.com/place-photos/AJRVUZOaQf8xlG2_eXrGA5taZ209wfUJB56CaknZHBMlyeosdU_UIBNXglSlcM25L8y5JNNGE8xJnD4Jvi5Pe4gj6PEBpzxBEWmFrWzSGnTBWAPYgi652iE1ez1gbUAocCch0trKOubvuuikIPPgJw=s4800-w1600",
    officialSourceUrl: "https://www.alnabaa.com/contact-us",
  },
  {
    id: "dealer_adata_02",
    slug: "adata-al-nabaa-mansoor",
    name: "AL-NABAA — Mansoor",
    brand: "ADATA",
    brandSlug: "adata",
    area: "شارع الصناعة",
    category: "PC Parts",
    categories: ["PC Parts", "Computing", "Accessories", "Chargers"],
    address: "Street AL-NABAA Building, Abu Jaafar Mansour, Baghdad, Baghdad Governorate, Iraq",
    phone: "0774 802 5119",
    lat: 33.3246271,
    lng: 44.3485332,
    googleMapsUrl: "https://maps.google.com/?cid=16637626013493649758",
    website: "https://www.alnabaa.com/",
    mainImage: "https://lh3.googleusercontent.com/place-photos/AJRVUZPDXJ3_BYiOwlL3bLDD2YeL2We13CId2r6qV18lDz53OpxSYBR20bxNVkgCd9rj6F621QJh5Q56ds5uJZrJlDxsLDMvHJ5ifGafp_EHeVSxtg1yZcuzG9-DCc0rXeyM6q4DJrrYFQzZuHkMGw=s4800-w1600",
    officialSourceUrl: "https://www.alnabaa.com/contact-us",
  },
  {
    id: "dealer_adata_03",
    slug: "adata-al-nabaa-babil",
    name: "AL-NABAA — Babil",
    brand: "ADATA",
    brandSlug: "adata",
    area: "شارع الصناعة",
    category: "PC Parts",
    categories: ["PC Parts", "Computing", "Accessories", "Chargers"],
    address: "Babil, Iraq",
    phone: "0771 308 2627",
    lat: 32.488092099999996,
    lng: 44.4277284,
    googleMapsUrl: "https://maps.google.com/?cid=8229241705751705273",
    website: "https://www.alnabaa.com/",
    mainImage: "https://lh3.googleusercontent.com/place-photos/AJRVUZMikm6AoN0SCiH1jjgBq6qY8LcwgvQc5Ap4u755hOqib88l3yYHGyy2qWcyU8guqKuOA42TezETmH0fNUCF6Hzxw49GDBAxi8Xj1nnFwyxQF03frxtX0UleH8GqrnzqWPeaAfHg3uwrcUkjPdM=s4800-w1600",
    officialSourceUrl: "https://www.alnabaa.com/contact-us",
  },
  {
    id: "dealer_adata_04",
    slug: "adata-al-nabaa-mosul",
    name: "AL-NABAA — Mosul",
    brand: "ADATA",
    brandSlug: "adata",
    area: "شارع الصناعة",
    category: "PC Parts",
    categories: ["PC Parts", "Computing", "Accessories", "Chargers"],
    address: "بناية مجموعة النبع - شارع المجموعة الثقافية مقابل جامعة, Mosul, Nineveh Governorate, 41001, Iraq",
    phone: "0770 161 5346",
    lat: 36.3739674,
    lng: 43.1418408,
    googleMapsUrl: "https://maps.google.com/?cid=17584646608266489531",
    website: "https://www.alnabaa.com/",
    mainImage: "https://lh3.googleusercontent.com/place-photos/AJRVUZPYi0vfoCSdXIvWVH4VrJ6yhJbhs1Z4NWab-k2eax_xyRSUTdnf1aeuR-3F36kJQAenkiQ6ENLANaZl6SHXWpJM2jL1B1bNcOVUHYs1nqTsSNOPcAs6HZoO3k6wFgo9SxvLGr8vIVoJH75h=s4800-w1600",
    officialSourceUrl: "https://www.alnabaa.com/contact-us",
  },
];
